# Global settings applied to the whole site.
# “base” is directory to change to before starting build, and
# “public” is the directory to publish (relative to root of your repo).
# “command” is your build command.

[build]
  base    = ""
  publish = "build/docs/javadoc"
  command = "./gradlew orchidBuild -Penv=prod"