site:
  about:
    siteName: 'Orchid Starter'
    subtitle: 'Basic starter repo to get going with Orchid quickly'
    siteDescription: 'This is a short blurb you can set below this index layouts sidebar.'
    avatar: '/assets/media/logo.jpg'

theme:
  social:
    facebook: 'facebookUsername'
    twitter: 'twitterHandle'
    instagram: 'instagramHandle'
    github: 'githubUsername'
    other:
      - label: 'linkedin'
        link: 'https://www.example.com'
        icon: 'fa-tag'
  menu:
    - type: 'page'
      title: 'Home'
      url: '/'
    - type: 'taxonomy'
      taxonomyType: 'categories'
      includeTerms: true
      termsAtRoot: true
    - type: 'wikiSections'
      atRoot: true
    - type: 'page'
      title: 'About'
      itemId: 'Author One'
  sidebar:
    - type: recentPosts
      limit: 3
      category: gallery
      noWrapper: true
      templates:
        - 'includes/postPreview_mini'
    - type: recentPosts
      limit: 5
      category: personal
      noWrapper: true
      templates:
        - 'includes/postPreview_list'
    - type: form
      form: prayer
      noWrapper: true
  extraCss:
    - 'assets/css/extraCss.scss'
    - 'assets/css/pygments.scss'
  extraJs:
    - 'assets/js/extraJs.js'

services:
  generators:
    disabled:
      - 'javadoc'
      - 'changelog'
      - 'styleguide'